# Generated by Django 4.2 on 2026-05-06 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('', 'Unknown')], max_length=5)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, help_text='kg', max_digits=5, null=True)),
                ('allergies', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('serial_no', models.CharField(blank=True, max_length=50)),
                ('chief_complaint', models.TextField(blank=True, verbose_name='Chief Complaint / History')),
                ('diagnosis', models.TextField(blank=True)),
                ('investigations', models.TextField(blank=True, help_text='Blood test, X-ray, etc.')),
                ('advice', models.TextField(blank=True, verbose_name='Advice / Notes')),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='prescriptions.patient')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_medicine', models.CharField(blank=True, help_text='If not in catalog', max_length=300)),
                ('dosage', models.CharField(blank=True, max_length=200)),
                ('frequency', models.CharField(blank=True, choices=[('1+0+0', '1+0+0 (Morning only)'), ('0+1+0', '0+1+0 (Noon only)'), ('0+0+1', '0+0+1 (Night only)'), ('1+0+1', '1+0+1 (Morning & Night)'), ('1+1+0', '1+1+0 (Morning & Noon)'), ('1+1+1', '1+1+1 (Three times daily)'), ('1+1+1+1', '1+1+1+1 (Four times daily)'), ('sos', 'SOS (As needed)'), ('custom', 'Custom')], max_length=20)),
                ('duration', models.CharField(blank=True, help_text='e.g. 7 days, 2 weeks', max_length=100)),
                ('instructions', models.CharField(blank=True, help_text='e.g. After meal', max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_items', to='medicines.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
