# Generated by Django 4.2 on 2026-05-06 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Medicine Categories',
                'ordering': ['name'],
                'unique_together': {('doctor', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('generic_name', models.CharField(blank=True, max_length=300)),
                ('manufacturer', models.CharField(blank=True, max_length=300)),
                ('dosage_form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('cream', 'Cream / Ointment'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('suppository', 'Suppository'), ('powder', 'Powder'), ('patch', 'Patch'), ('other', 'Other')], default='tablet', max_length=50)),
                ('strength', models.CharField(blank=True, help_text='e.g. 500mg, 10mg/5ml', max_length=100)),
                ('default_dosage', models.CharField(blank=True, help_text='e.g. 1+0+1 (morning, noon, night)', max_length=200)),
                ('default_duration', models.CharField(blank=True, help_text='e.g. 7 days, 2 weeks', max_length=100)),
                ('default_instructions', models.CharField(blank=True, help_text='e.g. After meal', max_length=300)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='medicines.medicinecategory')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
